services:
  agent:
    build: .
    container_name: strands-codeops-agent
    env_file:
      - .env
    volumes:
      - ./:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8088:8088"
    restart: unless-stopped
