# docker-compose.yml
services:
  agent:
    build: .
    container_name: strands-codeops-agent
    env_file:
      - .env
    volumes:
      - ./:/workspace
      - ./templates:/workspace/templates:ro   # <-- makes your templates visible in the container
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /workspace
    ports:
      - "8088:8088"
    restart: unless-stopped
