services:
  agent:
    build:
      context: .
    container_name: strands-codeops-agent
    env_file:
      - .env
    environment:
      # Logs & timeline
      LOG_LEVEL: ${LOG_LEVEL:-DEBUG}
      VERBOSE_RUN: ${VERBOSE_RUN:-1}

      # Force non-AWS provider & block IMDS noise
      AWS_EC2_METADATA_DISABLED: "true"
      AWS_METADATA_SERVICE_TIMEOUT: "1"
      AWS_METADATA_SERVICE_NUM_ATTEMPTS: "1"
      BOTO_CONFIG: /dev/null

      # Model routing -> Ollama on the host
      STRANDS_MODEL_PROVIDER: "ollama"
      OLLAMA_HOST: "http://host.docker.internal:11434"
      STRANDS_MODEL: "${STRANDS_MODEL:-qwen2.5-coder:3b}"

    # Helps Linux users; harmless on macOS
    extra_hosts:
      - "host.docker.internal:host-gateway"

    command: uvicorn fastapi_app:app --host 0.0.0.0 --port 8088 --reload
    working_dir: /workspace
    ports:
      - "8088:8088"
    volumes:
      - ./:/workspace
      - ./templates:/workspace/templates:ro
      - ./jobs:/workspace/jobs
      - /var/run/docker.sock:/var/run/docker.sock

    # Healthcheck: app AND Ollama must both be up
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -sf http://localhost:8088/health >/dev/null && OURL=$${OLLAMA_HOST:-http://host.docker.internal:11434} && curl -sf \"$${OURL}/api/tags\" >/dev/null"
        ]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 10s

    restart: unless-stopped
    tty: true
    stdin_open: true

    # Compose v2.22+ — live sync/rebuild
    develop:
      watch:
        - path: .
          target: /workspace
          action: sync
          ignore:
            - .git/
            - .idea/
            - .vscode/
            - __pycache__/
            - "**/*.pyc"
            - .pytest_cache/
            - jobs/
            - .venv/
            - jobs/*
        # 2) Rebuild the image if Python deps or base image change

        - path: requirements.txt
          action: rebuild
        - path: Dockerfile
          action: rebuild
        - path: templates
          target: /workspace/templates
          action: sync