
id: "REQ-1234"
title: "Add /health endpoint"
language: "python"
repo:
  url: "https://github.com/vappador/strands-demo.git"
  default_branch: "main"
branch:
  feature_id: "1234"
  name_template: "feature/{feature_id}-health"
build:
  container_image: "python:3.11-slim"
  workdir: "/workspace"
  command: |
    bash -lc "pip install -U pip &&         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi &&         pytest -q"
  env: {}
  timeout_seconds: 900
  cpu_shares: 512
  mem_limit: "2g"
codegen:
  description: |
    Look at the director structures, create test cases for the various python files that are in the repo, update the docker compose to 
    have a test option enabled.
  test_expectations:
    - Ensure that the test cases pass
    - Ensure that there is test coverage is at 80% at a minimum
github:
  create_pr: true
  base: "main"
  reviewers: ["maintainers"]
  labels: ["feature", "automation"]
  draft: false
